_BASE_: [
  "co_dino_r50_1x_coco.yml"
]

weights: output/co_dino_swin_tiny_1x/model_final
find_unused_parameters: True
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/swin_large_patch4_window12_384_22kto1k_pretrained.pdparams

CO_DETR:
  backbone: SwinTransformer

SwinTransformer:
  arch: 'swin_L_384' # ['swin_T_224', 'swin_S_224', 'swin_B_224', 'swin_L_224', 'swin_B_384', 'swin_L_384']
  out_indices: [0, 1, 2, 3]
  ape: false
  drop_path_rate: 0.3
  patch_norm: true

ChannelMapper:
  in_channels: [192, 384, 768, 1536]

LearningRate:
  base_lr: 0.0001

worker_num: 1
TrainReader:
  batch_size: 1
