_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/co_detr_r50.yml',
  '_base_/co_detr_reader.yml',
]
weights: output/co_detr_r50_1x/model_final
find_unused_parameters: True

TrainDataset:
  allow_empty: True
